### ISSUE TITLE
World Map - Should be able to Wrap Horizontally

### ISSUE THREAD

**Issue by QuintillusCFC** [C7-Game/Prototype#105]
The World Map should be able to wrap horizontally.  Right now, it cannot.

I know there has been some brainstorming about this, but don't recall the outcome of that.

If the same solution enables easy vertical scrolling, great, but if not, that can be spun off and is probably a much lower priority (has anyone made a vertical scrolling Civ map?).

**Comment by JimOfLeisure** [comment]
Last I saw, it *can* wrap horizontally and has been able to for a while now, but for devtime use it was easier to not wrap, so it's turned off. There's a boolean somewhere...looking for it now.

**Comment by JimOfLeisure** [comment]
It's not as obvious as it used to be, but it's still there. <https://github.com/C7-Game/Prototype/blob/c78b9804df659b774d310f53b3bced15753a4a2d/C7GameData/GameMap.cs#L15> - change the `wrapHorizontally` declaration to initialize as `true` and rerun; it will wrap.

We're just currently never trying to assign `wrapHorizontally` to anything besides its default `false`. So I guess we do need to ensure we're pulling that out of the SAV properly, if that's even an option in Civ3...I don't even recall if you can have a non-X-wrapped world or choose Y-wrapping as well, but C7 can do both. Or either. Or none.

**Comment by QuintillusCFC** [comment]
Oh, awesome!  I must have missed that back in the day, or forgotten it.  It most definitely works.  I'd vote for enabling it for maps where it is supposed to be enabled, if we don't still need it un-wrapped for some reason.  I've been enhancing the debug info printed out when you right-click a tile, so if it was for counting tiles, it's less likely we'll need it now.

Civ3 does have non-wrapping maps, was just playing one as a matter of fact.  Its editor allows Y-wrapped maps, but I don't know how that works in practice.  Same with both-wrapped.  I really want to play a Civ4 toroidal map someday since it shows the map curvature when you zoom out far enough.  Don't know what Civ3 does.

Leave open but only because of the "maybe this should be enabled by default" point.

**Comment by QuintillusCFC** [comment]
This got done for Babylon as part of PR #146 .  Looks like we missed closing the loop on the issue.  Closing now.
