### ISSUE TITLE
Refactor Popup Support so it's general-purpose reusable

### ISSUE THREAD

**Issue by QuintillusCFC** [C7-Game/Prototype#11]
11/15 - Basics done.  Can add some more things like figuring out the "selected" text color, and general-purpose confirm/cancel buttons.  But functions shared by 2+ popups (currently) are now in PopupOverlay.cs.

**Comment by QuintillusCFC** [comment]
This reminds me that the refactorings I mentioned above are still to do in the general code.  Glad I wrote it down so I didn't forget about them forever.

**Comment by QuintillusCFC** [comment]
The selected/focused/hover text colors are now sorted, thanks to theming updates.  Debating how much of the other stuff should be done now, leaning towards it not being a top area of priority.  Remaining things:

 - General-purpose confirm/cancel.  We only have these in one place (build city) right now, so it seems low priority.
 - Single click selects, double click does stuff, like in Civ.  Right now, single click does stuff.  TBH, I kind of like that single click does stuff, it saves mouse clicks.  But we should at least have a mode for that.

**Comment by QuintillusCFC** [comment]
Moving the remainder to Babylon 0.1.  Maybe we should put it farther out than that even.

**Comment by pcen** [comment]
https://github.com/C7-Game/Prototype/pull/69 takes some more steps to make popups general purpose, but there's still more refactoring to do

**Comment by QuintillusCFC** [comment]
I'm going to close this as two iterations of improvements have already been made to this, and at least right now it isn't a pain point.  We should generally favor small issues than ones that live forever, and split off new ones to cover step 2, step 3, etc. if needed.
