### ISSUE TITLE
Nuisance current_dir and current_path variables in SetCiv3HomeDialog

### ISSUE THREAD

**Issue by maxpetul** [C7-Game/Prototype#142]
The "SetCiv3HomeDialog" node's current_dir and current_path variables get reset each time the project is built to point to the current C7 project directory. These vars are then saved in MainMenu.tscn and might be accidentally included as part of an unrelated commit. See discussion here: https://github.com/C7-Game/Prototype/pull/126#pullrequestreview-906678307.

**Comment by pcen** [comment]
this Godot change https://github.com/godotengine/godot/pull/54399 will resolve this issue eventually, but it looks like the only workaround in the meantime would create the popup at runtime

**Comment by WildWeazel** [comment]
Yeah, this is one of those things I had in mind for local configuration. I don't know how Godot would do something like this but most build systems allow for some kind of secondary config or script that's intended to be per user and kept out of source control. Then you just reference those compile-time variables in your code. I'll look into it.
