### ISSUE TITLE
Build server can't build with tests at net6.0

### ISSUE THREAD

**Issue by QuintillusCFC** [C7-Game/Prototype#307]
Currently, the build server fails if the tests use net6.0, likely because its Docker image uses Mono, which imitates net4.7.2.

We should figure out a way to fix this, maybe:

 - Add a step to fetch net6.0 and build using that?
 - Figure out why the tests need to be on net6.0, and find a way to go back to net4.7.2
 - Something else?

**Comment by WildWeazel** [comment]
@JimOfLeisure had mentioned some interest in this

**Comment by QuintillusCFC** [comment]
This wound up being a semi-blocker to copying all the assets at once.  So, I'm looking at it now, with TheOrioli's solution.  Seems to be working.  Now trying to DRY out the configuration.
