### ISSUE TITLE
Add optional gzip compression to C7SaveFormat.Save() and .Load()

### ISSUE THREAD

**Issue by QuintillusCFC** [C7-Game/Prototype#33]
Not necessarily an Aztec 0.0 target

**Comment by QuintillusCFC** [comment]
Moving to Babylon.

**Comment by QuintillusCFC** [comment]
I've been playing around with compression some.  There's a lot of potential space saving here.  With a basic (non-optimized) LZW compression that I wrote in C# just now, almost 91% of the space can be saved; with ZIP compression (which uses the same core algorithm as GZIP), over 98% of the space can be saved.  I'm not really surprised; there's a lot of repetition, noticeably in the terrain types being duplicated for each tile.

FWIW, based on what I know now, I'd favor regular ZIP over GZIP, since regular ZIP has built-in OS support on Windows, whereas GZIP requires third-party utilities.  I believe ZIP should also be easy enough to work with on Linux?

**Comment by WildWeazel** [comment]
Yes, ZIP works on Linux these days

**Comment by QuintillusCFC** [comment]
Moving to Carthage... probably more appropriate to group with the save/load work that we have planned for that release.
