### ISSUE TITLE
Cities that Can't Supply Enough Food Grow Negatively Forever

### ISSUE THREAD

**Issue by QuintillusCFC** [C7-Game/Prototype#343]
Best illustrated with a screenshot:

![image](https://user-images.githubusercontent.com/5287977/185180034-5a776aef-2b6c-4e52-b63a-744849569812.png)

Rome grew to size 2 but couldn't supply enough food, so every turn the counter of how long until it grows decreases by 1.  Instead it should shrink to size 1.

**Comment by WildWeazel** [comment]
Related: In civ3 the city tile has a minimum yield of 2/1/1 (is it affected by food consumption per citizen?) so it's impossible to starve below size 1.

**Comment by QuintillusCFC** [comment]
We do have the 2/1 food/prod minimum, although commerce is 3 for some reason (I thought that was the min?  or maybe only for the capital?).  But C7 cities shouldn't be starving below size 1; in this case Rome had 3 food total for 2 citizens.

I do not know whether that 2/1/(1/3) is affected by food consumed per citizen; it might be.

**Comment by QuintillusCFC** [comment]
Currently this can be reproduced on the 295_City_Production_Adjustment branch.  Settle in place, and by turn 100 (even with a Worker being built) Carthage will reach this state.

**Comment by WildWeazel** [comment]
Interesting results: if food consumption is 1 or 2, the city tile produces the same number. If 3+, it produces 1 less than consumption, making it possible for the last population to starve. When this happens the city turns to ruins as if razed. If your last city starves, you _win_ a conquest victory. I'm not sure what to do with that information or how faithful we want to be, but there you go.

**Comment by QuintillusCFC** [comment]
You do indeed win a conquest victory if your last city is destroyed, at least by non-military-related means... Chieftess discovered that around 2004 with the then-new volcanoes.

Interesting observations.  So if food consumption is 5, it produces 4, i.e. it's not a hard cap at 2 but always one less?

I would reckon only city destroyed = conquest victory to be an esoteric bug of Civ3.  We could have it as an option in a "legacy rule set", but I would not prioritize it.

**Comment by QuintillusCFC** [comment]
I don't know of anyone discovering that specific case of last-city-starvation-victory though... might be worth a C&C post for the "easter egg" nature of the discovery.

**Comment by WildWeazel** [comment]
> So if food consumption is 5, it produces 4, i.e. it's not a hard cap at 2 but always one less?

You know, I just realized I was observing the despotism tile penalty. So the rule is presumably yield = production and subject to the penalty if >2.

**Comment by QuintillusCFC** [comment]
Ahhh, the infamous despotism penalty.  That makes sense.

**Comment by QuintillusCFC** [comment]
This can be reproduced from today's Develop branch with seed 643368717; Carthage starts close enough to the target area to reproduce the issue.
