### ISSUE TITLE
Pressing Disband Multiple Times Duplicates Box

### ISSUE THREAD

**Issue by benskywalker** [C7-Game/Prototype#432]
When you press Disband multiple times while it is open, it duplicates the box. You can still interact with any of them properly and they do disappear. However, they will all reappear the next time you try to disband a unit
![image](https://github.com/C7-Game/Prototype/assets/12992619/2e5df4ae-bd3d-405b-aa54-6aad1bd2413a)

**Comment by pcen** [comment]
I think https://github.com/C7-Game/Prototype/pull/414 will resolve this

**Comment by QuintillusCFC** [comment]
I have confirmed that #414 fixes this, and it is now merged.
