### ISSUE TITLE
Carthage credits 

### ISSUE THREAD

**Issue by WildWeazel** [C7-Game/Prototype#436]
Update credits text with new contributors, licenses, thanks, etc

**Comment by WildWeazel** [comment]
I have a local copy with a shout out to the CFC admins and Civ3 creators. No new contributors that I can see since the last release. Did we add any new third-party components? @pcen @QuintillusCFC

**Comment by QuintillusCFC** [comment]
I don't see Serilog in the credits, I think it might be new since Babylon?  That's the only one that I can think of or find.

**Comment by WildWeazel** [comment]
I'm struggling to find a clear explanation of how to concisely credit unmodified dependencies that use standard licenses. The Apache license text is quite long and doesn't explicitly say how to cite _usage_ of the software. I can only imagine how long the credits would eventually become if we include the full text of every license instance of every dependency.

To be clear I'm not suggesting we omit any accreditation, even if it's not strictly required. I just want to avoid copy-pasting whole licenses over and over.

**Comment by QuintillusCFC** [comment]
> I'm struggling to find a clear explanation of how to concisely credit unmodified dependencies that use standard licenses. The Apache license text is quite long and doesn't explicitly say how to cite _usage_ of the software. I can only imagine how long the credits would eventually become if we include the full text of every license instance of every dependency.
> 
> To be clear I'm not suggesting we omit any accreditation, even if it's not strictly required. I just want to avoid copy-pasting whole licenses over and over.

According to https://www.apache.org/licenses/LICENSE-2.0#apply, it appears that it is sufficient to include the relatively short section within that section that has a link out to the main Apache license.

I'm also thinking that it is likely adequate to include one copy of each unique license.  E.g. something like:

```
Software Used in C7:

Library ABC, Apache License 2.0
Library DEF, Apache License 2.0
Library GHI, BSD 3-Clause License

Licenses:

Apache License 2.0

(Content from above link)

BSD 3-Clause License

(Content of BSD 3-Clause License)
```

Disclaimer: IANAL.  But from a common sense standpoint I think that would meet the criteria.

Somewhat longer term we could also have local links to bring up the text of licenses so it could read:

Library ABC, [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0)

If it gets to a point that the list is a bit excessively long.

**Comment by WildWeazel** [comment]
Since it's not (AFAIK) mandated that we show any licenses _at runtime_, I think I like the way VS Code does it: there's a file [ThirdPartyNotices.txt](https://github.com/microsoft/vscode/blob/main/ThirdPartyNotices.txt) at the project root with the full text of each one, but also they use this quasi-standard notation to cite each one, which we could include in the credits.

```
[project name] [version] - [license name]
[source url]

[full license text]
```

**Comment by WildWeazel** [comment]
reminder to add @TomWerner and probably @esbudylin by the time this rolls out!

**Comment by WildWeazel** [comment]
Closing for Carthage, but let's put a pin in the license discussion.
