### ISSUE TITLE
Wont run on macOS 15.0

### ISSUE THREAD

**Issue by xyeres** [C7-Game/Prototype#445]
<img width="372" alt="Screenshot 2024-09-25 at 10 46 00 AM" src="https://github.com/user-attachments/assets/31e6c0ea-90ec-4637-94d7-6416d8ddd3a6">

Getting "“C7” is damaged and can’t be opened. You should move it to the Trash." on macOS 15.0 on M1 mac mini

**Comment by WildWeazel** [comment]
See the workaround at the bottom of the release page: https://c7-game.github.io/#known-issues

**Comment by xyeres** [comment]
My bad, didn’t read the read me 🙈

**Comment by WildWeazel** [comment]
enjoy!
