### ISSUE TITLE
Adding dialog to select Civ3 Home if not detected

### ISSUE THREAD

**Issue by JimOfLeisure** [C7-Game/Prototype#48]

**Comment by JimOfLeisure** [comment]
Moved this back to To do after running into a challenge. Partial code is in civ3-home branch, but it needs to get rid of the overloaded Civ3MediaPath function and always have access to the civ3 home info. Which will be in GlobalSingleton, but I have yet to think of the "right" way to allow all the references across 11 files to fetch the value and pass it to the utility function.

Also, the MainMenu button to pick the dir needs some work to hide it if Civ3 Home is valid (media can load) and make it clickable if not. Plus it's ugly.

**Comment by QuintillusCFC** [comment]
@JimOfLeisure This is covered in https://github.com/C7-Game/Prototype/pull/78, right?

**Comment by JimOfLeisure** [comment]
> @JimOfLeisure This is covered in #78, right?

Yeah. I forgot about the task, but that branch & PR is exactly what this is about.

The button is still ugly, but the functionality is more important, and the no-civ3-home screen isn't particularly pretty, anyway. Also it needs its text updated to take this new button into account.
