### ISSUE TITLE
Wrap tilemap seamlessly in display

### ISSUE THREAD

**Issue by myjimnelson** [C7-Game/Prototype#5]
Have been experimenting in TileMap/TileMap.tscn standalone scene

- 87381ffa4b13cb8d46e353e14457c04ae6b54cfe - Scrolling via buttons with no wrap using KinematicBody2D with no texture or collision shape and Camera2D
- 479ba3d0ffd89a76b7e8f413bd36664760ccba54 - Can click & drag mouse to scroll and zoom with mouse wheel (no wrap)
- 42a93368545f3a21a0f709e30028957e3c9ba9ac - In Experiments/TwoNodesSameReferenceScroll.tscn tried to duplicate Node2D for seamless scrolling of test icon hoping that child nodes are referenced not duplicated
- 309351c3744fdc0f8e7beb7430eaf820f6c09b10 - Proof that the child nodes are duplicated and not the same, so this tactic probably not helpful

Ideas:

- Might be able to copy texture of [ViewPort](https://docs.godotengine.org/en/stable/classes/class_viewport.html) without re-rendering tiles; e.g. render once, steal the texture to draw in another Node2D
- Might segment map horizontally into chunks and have only the necessary chunk duplicated at any time; still duplication, but less of it
- Might segment map horizontally into different Node2Ds and just translate them as needed, but would reduce the max displayable width

**Comment by JimOfLeisure** [comment]
Flintlock has x and Y wrapping working with MapView and has for a while. It's redrawing tiles as the map scrolls.
