### ISSUE TITLE
Bonus Grassland Overlay

### ISSUE THREAD

**Issue by QuintillusCFC** [C7-Game/Prototype#90]
Add the bonus grassland overlay.

These use the "desert" TNT overlay, specifically the 4th row down (first row being row 1) in Art\Terrain\tnt.pcx.  I have not determined which one Civ uses, and in my editor use a deterministic calculation based on the tileIndex % 3.  I suggest we start with something equivalent; if someone really cares and knows how it's determined, great, but the important thing is it doesn't change every frame.

**Comment by JimOfLeisure** [comment]
I just put up #109 , not necessarily as fully ready to merge-in, but I wanted to show where the info was. Note my comments in that PR / commit.

That PR as-is only adds logic equivalent to the snow capped and pine forest logic but doesn't attempt to display the bonus.
