### ISSUE TITLE
Write Up How-to-Get-Started-with-Development Instructions

### ISSUE THREAD

**Issue by QuintillusCFC** [C7-Game/Prototype#95]
This should probably be in a GitHub Wiki (to be added), and linked from the main Readme.  Maybe we already have it somewhere, but if so I'm not sure off the top of my head.

Things to include:

 - How to download and compile.  Including that you'll need Godot Mono, latest 3.x
 - Recommended IDE setups that we can help you with (VSCode + Godot, Rider)
 - Link to the CFC discussion forum, as the main discussion area.  Probably to the Discord too.
 - Link to the "good first issue" issues, and note to open a pull request, probably from a fork initially for first-timers.

Maybe some other things I haven't thought of.

**Comment by WildWeazel** [comment]
I've been revising the wiki and I think this is all done.

**Comment by QuintillusCFC** [comment]
Yeah, I agree.  For a long time it felt like this was always a work-in-progress, but I think it covers it pretty well now.

**Comment by QuintillusCFC** [comment]
Well, all it took was closing the issue to realize I'd forgot to note that Rider needs the Godot Support plugin.  But now that's added, and we're pretty much caught up anyway, it'll be incremental changes going forward.
